### ISSUE TITLE
Predict output probabilities using predict_proba

### ISSUE THREAD

**Issue by sarin1991** [HDI-Project/MLPrimitives#130]
* MLPrimitives version: 0.1.5
* Python version: 3.7.1
* Operating System: Amazon Linux (4.14.88-88.76.amzn2.x86_64)

### Description
I have a use case where I need classification models to output probabilities instead of the predicted class.

For eg:
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier.predict_proba

To work around this, I had to create a custom block for each model and insert a new keyword for predict as shown below.
```python
from sklearn.ensemble import RandomForestClassifier

class RandomForestBlock(object):
    def __init__(self, **kwargs):
        self.kwargs = kwargs
        self.model = None

    def fit(self, X,y):
        self.model = RandomForestClassifier(**self.kwargs)
        self.model.fit(X,y)

    def predict(self, X, prob=False):
        if prob:
            return self.model.predict_proba(X)[:,1]
        else:
            return self.model.predict(X)
```
I was wondering if there is a better way to do this without writing custom code?
This will probably be a pretty common use case.

**Comment by csala** [comment]
Hello @sarin1991 

There is, indeed, a better way to do it :-)

As you know, in the JSON annotation we point at one particular method in the primitive instance to use during the `produce` phase. In most cases, this is the `predict` method, but in other cases you can point at a different method, such as `predict_proba`.

In cases like this, what we need is to create a new primitive annotation that is basically a copy of the other one that points at a different method. You can see this documented in detail here: https://hdi-project.github.io/MLPrimitives/community/annotations.html#creating-a-new-version-of-an-existing-annotation

For the RandomForestClassifier in particular this is already implemented in the [sklearn.ensemble.RandomForestClassifier_proba.json](https://github.com/HDI-Project/MLPrimitives/blob/master/mlprimitives/jsons/sklearn.ensemble.RandomForestClassifier_proba.json) primitive, but this hasn't been created yet for the other scikit-learn classifiers that we have integrated.
If you plan on using those, please feel more than welcome to contribute them!

**Comment by csala** [comment]
Closing this, as the question has already been responded.
