### ISSUE TITLE
Add Early Stopping to keras.Sequential.LSTMTimeSeriesRegressor primitive

### ISSUE THREAD

**Issue by AlexanderGeiger** [HDI-Project/MLPrimitives#156]
Add Early Stopping to `keras.Sequential.LSTMTimeSeriesRegressor` primitive as indicated in the paper that inspired its implementation: https://arxiv.org/pdf/1802.04431.pdf

The exact arguments for the early stopping should be the ones indicated in the [telemanom config.yaml file](https://github.com/khundman/telemanom/blob/master/config.yaml), which were the ones used during the experiments explained in the paper:

* `patience`: 10
* `min_delta`: 0.0003

**Comment by csala** [comment]
This can be done alongside #159
