### ISSUE TITLE
Add anomaly threshold calculation for batches of errors

### ISSUE THREAD

**Issue by AlexanderGeiger** [HDI-Project/MLPrimitives#158]
### Description

The calculation of the threshold ε in the _timeseries_anomalies.py_ primitive should happen in batches, i.e. the threshold should be calculated for each batch of errors separately. Currently we are using the whole array of errors to calculate one single threshold.

**Comment by csala** [comment]
This will be covered by #160

**Comment by csala** [comment]
Covered in #160
