### ISSUE TITLE
Add sklearn.neighbors primitives

### ISSUE THREAD

**Issue by wsnalice** [HDI-Project/MLPrimitives#38]
I would like to add some primitives from sklearn.neighbors

Primitives to add:
- sklearn.neighbors.KNeighborsClassifier
- sklearn.neighbors.KNeighborsClassifier_proba
- sklearn.neighbors.KNeighborsRegressor

**Comment by csala** [comment]
I just assigned this you @wsnalice 

Also, would you mind adding the exact list of primitives to the description?

**Comment by wsnalice** [comment]
> I just assigned this you @wsnalice
> 
> Also, would you mind adding the exact list of primitives to the description?

Added!

**Comment by csala** [comment]
Closed via #40
