### ISSUE TITLE
Pip install requirements_dev.txt fail

### ISSUE THREAD

**Issue by wsnalice** [HDI-Project/MLPrimitives#39]
### Description

In the Contributing page, some instruction fails.

### What I Did

`pip install -r requirements_dev.txt`
`Could not open requirements file: [Errno 2] No such file or directory: 'requirements_dev.txt'`

**Comment by csala** [comment]
Sorry for the confusion @wsnalice.

The contributing documentation is being updated (Issue #7), and the installation instructions are actually out of date.

The right way to install the library for development is using the command `pip install -e .[dev]`.
