### ISSUE TITLE
Add Primitives for Error calculation, smoothing, and thresholding

### ISSUE THREAD

**Issue by itinawi** [HDI-Project/MLPrimitives#48]
I want to add primitives for dynamic error calculation, smoothing, and thresholding. 

I will be adding the code for these functions to MLPrimitives as its own python file, to be called MLPrimitives/mlprimitives/**dynamic_error_thresholding.py**

The implementation is as per Section 3.2 of : https://arxiv.org/pdf/1802.04431.pdf

dynamic_error_thresholding.py software architecture:

It will be a Python class called `ErrorThresholder`
which is initialized with 
- `y_true` (np array): array of test targets corresponding to true values to be predicted at end of each sequence
- `y_hat` (np array): predicted test values for each timestep in `y_test`
- `smoothed` (bool): If False, return unsmooothed errors (used for assessing quality of predictions)
Some parameters that have default values:
- `BATCH_SIZE` = 70        # number of values to evaluate in each batch
- `WINDOW_SIZE` = 30       # number of trailing batches to use in error calculation
- `SMOOTHING_PERC` = 0.05  # determines window size used in EWMA smoothing (percentage of total values for channel)

Methods:
- get_errors(inputs `y_true` and `y_hat` from self, `smoothed` (boolean)), returns `errors` (list of errors) Calculate the difference between predicted telemetry values and actual values, then smooth residuals using ewma to encourage identification of sustained errors/anomalies.

- process_errors(inputs: `y_true` and `y_hat`, `smoothed_errors`) 
returns `sequence_anomalies` (a list of anomalies detected from the errors) and anomaly_scores (score for each anomaly sequence).

- other helper methods for these two functions, as needed

**Comment by kveerama** [comment]
@itinawi what would be the outputs? For example for the method process_errors?

**Comment by itinawi** [comment]
The output would be a list of lists/tuples indicating the start and end time of anomalous sequences

**Comment by csala** [comment]
Closed via #58
