### ISSUE TITLE
sklearn.impute.SimpleImputer primitive

### ISSUE THREAD

**Issue by csala** [HDI-Project/MLPrimitives#72]
The old `sklearn.preprocessing.Imputer` is deprecated and should be replaced with the new `sklearn.impute.SimpleImputer` one, which needs to be integrated as a new primitive.

When adding the new one there is no need to remove the old one, but the dependencies should be indicated appropriately on each one of them.

**Comment by Hector-hedb12** [comment]
I would like to work on this
