### ISSUE TITLE
Add Primitive for sklearn.linear_model.LinearRegression

### ISSUE THREAD

**Issue by itinawi** [HDI-Project/MLPrimitives#85]
MLPrimitives would benefit from adding a linear regressor

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression

**Comment by csala** [comment]
@itinawi Can you keep this issue only for the LinearRegression and move the second paragraph to new issues?
